Add readme
djrenren/battlegrid pull request #2
Opened 2022-02-11 05:57 UTC by 7imbrook

2022-02-16 02:50 UTC, djrenren requested changes

2022-02-16 02:50 UTC, djrenren commented on README.md
> +Battle grid is a perr-to-peer tile canvan meant to be multi purpose and used as a tool in games like dnd. To add objects to the canvas drag and drop an image from your computer. To set the back drop,
What is a perr?

2022-02-16 14:40 UTC, johndg0019 commented on README.md
> +Battle grid is a perr-to-peer tile canvan meant to be multi purpose and used as a tool in games like dnd. To add objects to the canvas drag and drop an image from your computer. To set the back drop,
What is a canvan?

2022-07-10 02:09 UTC, 7imbrook reviewed
Speeling is herd

2022-07-11 19:46 UTC, djrenren approved these changes

2022-07-11 19:46 UTC, merged